/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextureCubeRouteImport } from './routes/textureCube'
import { Route as RotatingCubeRouteImport } from './routes/rotatingCube'
import { Route as InstancedCubeRouteImport } from './routes/instancedCube'
import { Route as HelloTriangleRouteImport } from './routes/helloTriangle'
import { Route as FractalCubeRouteImport } from './routes/fractalCube'
import { Route as CubemapRouteImport } from './routes/cubemap'
import { Route as ComputeShaderRouteImport } from './routes/computeShader'
import { Route as IndexRouteImport } from './routes/index'

const TextureCubeRoute = TextureCubeRouteImport.update({
  id: '/textureCube',
  path: '/textureCube',
  getParentRoute: () => rootRouteImport,
} as any)
const RotatingCubeRoute = RotatingCubeRouteImport.update({
  id: '/rotatingCube',
  path: '/rotatingCube',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancedCubeRoute = InstancedCubeRouteImport.update({
  id: '/instancedCube',
  path: '/instancedCube',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloTriangleRoute = HelloTriangleRouteImport.update({
  id: '/helloTriangle',
  path: '/helloTriangle',
  getParentRoute: () => rootRouteImport,
} as any)
const FractalCubeRoute = FractalCubeRouteImport.update({
  id: '/fractalCube',
  path: '/fractalCube',
  getParentRoute: () => rootRouteImport,
} as any)
const CubemapRoute = CubemapRouteImport.update({
  id: '/cubemap',
  path: '/cubemap',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeShaderRoute = ComputeShaderRouteImport.update({
  id: '/computeShader',
  path: '/computeShader',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/computeShader': typeof ComputeShaderRoute
  '/cubemap': typeof CubemapRoute
  '/fractalCube': typeof FractalCubeRoute
  '/helloTriangle': typeof HelloTriangleRoute
  '/instancedCube': typeof InstancedCubeRoute
  '/rotatingCube': typeof RotatingCubeRoute
  '/textureCube': typeof TextureCubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/computeShader': typeof ComputeShaderRoute
  '/cubemap': typeof CubemapRoute
  '/fractalCube': typeof FractalCubeRoute
  '/helloTriangle': typeof HelloTriangleRoute
  '/instancedCube': typeof InstancedCubeRoute
  '/rotatingCube': typeof RotatingCubeRoute
  '/textureCube': typeof TextureCubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/computeShader': typeof ComputeShaderRoute
  '/cubemap': typeof CubemapRoute
  '/fractalCube': typeof FractalCubeRoute
  '/helloTriangle': typeof HelloTriangleRoute
  '/instancedCube': typeof InstancedCubeRoute
  '/rotatingCube': typeof RotatingCubeRoute
  '/textureCube': typeof TextureCubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/computeShader'
    | '/cubemap'
    | '/fractalCube'
    | '/helloTriangle'
    | '/instancedCube'
    | '/rotatingCube'
    | '/textureCube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/computeShader'
    | '/cubemap'
    | '/fractalCube'
    | '/helloTriangle'
    | '/instancedCube'
    | '/rotatingCube'
    | '/textureCube'
  id:
    | '__root__'
    | '/'
    | '/computeShader'
    | '/cubemap'
    | '/fractalCube'
    | '/helloTriangle'
    | '/instancedCube'
    | '/rotatingCube'
    | '/textureCube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComputeShaderRoute: typeof ComputeShaderRoute
  CubemapRoute: typeof CubemapRoute
  FractalCubeRoute: typeof FractalCubeRoute
  HelloTriangleRoute: typeof HelloTriangleRoute
  InstancedCubeRoute: typeof InstancedCubeRoute
  RotatingCubeRoute: typeof RotatingCubeRoute
  TextureCubeRoute: typeof TextureCubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/textureCube': {
      id: '/textureCube'
      path: '/textureCube'
      fullPath: '/textureCube'
      preLoaderRoute: typeof TextureCubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotatingCube': {
      id: '/rotatingCube'
      path: '/rotatingCube'
      fullPath: '/rotatingCube'
      preLoaderRoute: typeof RotatingCubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instancedCube': {
      id: '/instancedCube'
      path: '/instancedCube'
      fullPath: '/instancedCube'
      preLoaderRoute: typeof InstancedCubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helloTriangle': {
      id: '/helloTriangle'
      path: '/helloTriangle'
      fullPath: '/helloTriangle'
      preLoaderRoute: typeof HelloTriangleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fractalCube': {
      id: '/fractalCube'
      path: '/fractalCube'
      fullPath: '/fractalCube'
      preLoaderRoute: typeof FractalCubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cubemap': {
      id: '/cubemap'
      path: '/cubemap'
      fullPath: '/cubemap'
      preLoaderRoute: typeof CubemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computeShader': {
      id: '/computeShader'
      path: '/computeShader'
      fullPath: '/computeShader'
      preLoaderRoute: typeof ComputeShaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComputeShaderRoute: ComputeShaderRoute,
  CubemapRoute: CubemapRoute,
  FractalCubeRoute: FractalCubeRoute,
  HelloTriangleRoute: HelloTriangleRoute,
  InstancedCubeRoute: InstancedCubeRoute,
  RotatingCubeRoute: RotatingCubeRoute,
  TextureCubeRoute: TextureCubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
